version: '3.9'

services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: wallet_user
      POSTGRES_PASSWORD: wallet_pass
      POSTGRES_DB: wallet_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U wallet_user"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      BASE_URL_DB: postgresql+asyncpg://wallet_user:wallet_pass@db:5432/wallet_db
    command: >
      sh -c "alembic upgrade head &&
             uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"

volumes:
  postgres_data: